version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: url_redirector
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf